# tmux options
set -g display-time 4000
set -g status-interval 5
set -g focus-events on

# Fix colors
set -g default-terminal "screen-256color"
set -as terminal-features ",*:RGB"
set -ag terminal-overrides ",xterm-256color:RGB"

# remap prefix from 'C-b' to 'C-`'
# unbind C-b
# set -g prefix "C-`"
# bind "C-`" send-prefix

# start windows and panes at index 1, not 0
set -g base-index 1
setw -g pane-base-index 1
set-option -g renumber-windows on

# Move between windows with Ctrl+Shift+arrow without prefix
bind-key -n M-Left previous-window
bind-key -n M-Right next-window

# Quick jump to windows with Alt-[Num] without prefix
bind-key -n M-1 select-window -t 1
bind-key -n M-2 select-window -t 2
bind-key -n M-3 select-window -t 3
bind-key -n M-4 select-window -t 4
bind-key -n M-5 select-window -t 5
bind-key -n M-6 select-window -t 6
bind-key -n M-7 select-window -t 7
bind-key -n M-8 select-window -t 8
bind-key -n M-9 select-window -t 9
bind-key -n M-0 select-window -t 10

# split panes using | and _
bind | split-window -h
bind _ split-window -v
unbind '"'
unbind %

# switch panes using Alt-arrow without prefix
bind -n C-S-Left select-pane -L
bind -n C-S-Right select-pane -R
bind -n C-S-Up select-pane -U
bind -n C-S-Down select-pane -D

# Enable mouse control
set -g mouse on


# DESIGN TWEAKS

# don't do anything when a 'bell' rings
# set -g visual-activity off
# set -g visual-bell off
# set -g visual-silence off
# setw -g monitor-activity off
# set -g bell-action none

# clock mode
# setw -g clock-mode-colour #d7a64b

# copy mode
# setw -g mode-style 'fg=black bg=#c72138 bold'

# panes
set -g pane-border-style 'fg=#c72138'
set -g pane-active-border-style 'fg=#d7a64b'

# Status Line(s)
set -g status-position bottom
set -g status-justify left
set -g status-style 'bg=#202020'

# set -g status-left-style 'bg=#202020 fg=#d7a64b'
set -g status-left '#[bg=#202020,fg=#d7a64b] #S '
set -g status-left-length 20

# set -g status-right-style 'bg=#202020'
set -g status-right ''
# set -g status-right-length 50
setw -g window-status-separator ''

setw -g window-status-current-style 'fg=#202020,bg=#d7a64b'
setw -g window-status-current-format '\
#[bg=#d7a64b,fg=#202020]\
#[bg=yello,fg=#202020] #I \
#[bg=#21314f,fg=#d7a64b]\
#[bg=#21314f,fg=white] #W \
#[bg=#202020,fg=#21314f]\
'
setw -g window-status-style 'fg=gray'
setw -g window-status-format '\
#[bg=#304c7a,fg=#202020]\
#[bg=#304c7a,fg=gray] #I \
#[bg=#21314f,fg=#304c7a]\
#[bg=#21314f,fg=gray] #W \
#[bg=#202020,fg=#21314f]\
'

# setw -g window-status-bell-style 'fg=#d7a64b bg=#c72138 bold'

# messages
set -g message-style 'fg=#d7a64b bg=#c72138 bold'


# Plugin configs
run 'for file in ~/.config/tmux/plugin-conf/*.conf; do tmux source-file "$file"; done'

# Plugins
set -g @plugin 'omerxx/tmux-floax'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Initalize tpack (must always be the last line in this file)
run '~/.tmux/plugins/tpm/tpm'
